name: SSL-SuperResolution
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
dependencies:
  - python=3.9
  - numpy
  - scipy
  - pytorch
  - torchvision
  - tqdm
  - astropy
  - pillow
  - opencv
  - matplotlib
  - pandas
  - pip
  - pip:
      - scikit-image
      - scikit-learn
      - tensorboard